name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebase
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  firebase_crashlytics: ^2.0.0
  firebase_performance: ^0.7.0+3

  # For Architecture
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4

  # For Networking
  dio: ^4.0.0
  dio_firebase_performance: ^0.3.1-dev.3
  # For User-Agent Client Hints
  ua_client_hints: ^1.0.3

  # For Model
  json_serializable: ^4.1.3
  freezed_annotation: ^0.14.2

  # For Navigation
  auto_route: ^2.2.0

  # For DateTime
  intl: ^0.17.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For UIs
  gap: ^2.0.0
  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4

  # For Assets
  flutter_gen_runner: ^3.1.1

  # For Navigation
  auto_route_generator: ^2.1.0

  # For Model
  freezed: ^0.14.2

  # For Analyzer
  effective_dart: ^1.3.0

  # For Testing
  mocktail: ^0.1.4
  mocktail_image_network: ^0.1.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
