name: app
description: Flutter Architecture Blueprints project.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # For DateTime and l10n
  intl: ^0.16.1

  # For Google and Firebase
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6

  # For Architecture
  flutter_hooks: ^0.14.1
  hooks_riverpod: ^0.12.1

  # For Networking
  dio: ^3.0.10
  dio_http_cache: ^0.2.11

  # For Model
  json_serializable: ^3.5.0
  freezed_annotation: ^0.12.0

  # For Key-Value local storage
  shared_preferences: ^0.5.12+4

  # Convert between Enum and String
  enum_to_string: ^1.0.13

  # For UIs
  gap: ^1.2.0
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  cached_network_image: ^2.3.3
  flutter_svg: ^0.19.2+1

  # For Utilities
  get: ^3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4

  # For Model
  freezed: ^0.12.2

  # For Analyzer
  effective_dart: ^1.3.0

  # For Testing
  mockito:
  image_test_utils:

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Rotunda
      fonts:
        - asset: assets/fonts/Rotunda-Bold.otf
          weight: 700
